# 方針
# - 基本的には全てのルールを有効にする。
# - 無効にしたいルールは個別に無効にし、理由をコメントに残す。
# - この方針により、常に最新のルールセットを使うことができる & 無効の理由をコード状に残すことができる

run:
  allow-parallel-runners: true

output:
  sort-results: true

linters:
  # 基本全て有効にする。無効にしたいものは個別に無効し理由をコメントに残す。
  enable-all: true
  fast: false # 全てのlinterを実行したいのでfalse
  disable:
    - deadcode # Deprecated
    - varcheck # Deprecated
    - interfacer # Deprecated
    - exhaustivestruct # Deprecated
    - scopelint # Deprecated
    - ifshort # Deprecated
    - nosnakecase # Deprecated
    - golint # Deprecated
    - maligned # Deprecated
    - structcheck # Deprecated
    - varnamelen # 変数名の長さをチェックするルール。短くするのが慣習なので無効。
    - exhaustruct # structの全てのフィールドが初期化されているかチェックするルール。初期化しないこともあるので無効。
    - gomnd # マジックナンバーを定数にするルール。定数にすると可読性が下がることもあるので無効s。
    - importas # importのエイリアスをつけるルール。goimportsと競合するので無効。
    - gci # importのformatとlinter。goimportsと競合するので無効。

# 下記に設定項目記載
# https://golangci-lint.run/usage/linters/
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/go-sql-driver/mysql

issues:
  # CIで実行するときはtrueにする。
  new: false
