name: go lint

on:
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: reviewdog/action-golangci-lint@v2
        with:
          go-version: '1.21'
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          cache: false
          golangci_lint_flags: "--config=.golangci.yaml"
          workdir: server/
