name: go lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  # lint
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.1
          working-directory: server/
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
